export enum QueryKeys {
  RecentPostsAndGames = "getRecentPostsAndGames",
  RecentPosts = "getRecentPosts",
  RecentLikedPosts = "getRecentLikedPosts",
  RecentGames = "getRecentGames",
  Comments = "getComments",
  Replies = "getReplies",
  Cities = "getCities",
  Users = "getUsers",
  WaitingGame = "getWaitingGame",
  JoinedGame = "getJoinedGame",
  Notifications = "getNotifications",
  Chats = "getChats",
  Messages = "getMessages",
  UsersYouMayKnow = "getUsersYouMayKnow",
  GamesNearby = "getGamesNearby",
  Likes = "getLikes",
}
